apiVersion: v1
kind: ConfigMap
data:
  DB_USERNAME: "ct_admin"
  DB_NAME: "geoconnections"
  DB_HOST: "postgres"
  DB_PORT: "5432"
  GRPC_URI: "locations-svc:5005"
  PERSONS_URI: "http://persons-svc:5000"
  KAFKA_URI: "kafka:9092"
  KAFKA_TOPIC: "connections"
metadata:
  name: api-env
