---
apiVersion: v1
kind: Service
metadata:
  name: zoo1
  labels:
    app: zookeeper-1
spec:
  ports:
    - name: client
      port: 2181
      protocol: TCP
    - name: follower
      port: 2888
      protocol: TCP
    - name: leader
      port: 3888
      protocol: TCP
  selector:
    app: zookeeper-1
---
kind: StatefulSet
apiVersion: apps/v1
metadata:
  name: zookeeper-deployment-1
spec:
  serviceName: zoo1
  replicas: 1
  selector:
    matchLabels:
      name: zookeeper-1
  template:
    metadata:
      labels:
        name: zookeeper-1
    spec:
      containers:
        - name: zoo1
          image: digitalwonderland/zookeeper
          ports:
            - containerPort: 2181
          env:
            - name: ZOOKEEPER_ID
              value: "1"
            - name: ZOOKEEPER_SERVER_1
              value: zoo1
          volumeMounts:
            - name: zookeeper-volume
              mountPath: "/var/lib/zookeeper"
      volumes:
        - name: zookeeper-volume
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: kafka-broker
  labels:
    app: kafka-broker-1
spec:
  ports:
    - port: 9092
      targetPort: 9092
      protocol: TCP
  selector:
    app: kafka-broker-1
  type: ClusterIP
---
kind: StatefulSet
apiVersion: apps/v1
metadata:
  name: kafka-deployment-1
spec:
  serviceName: kafka1
  replicas: 1
  selector:
    matchLabels:
      name: kafka-broker-1
  template:
    metadata:
      labels:
        name: kafka-broker-1
    spec:
      containers:
        - name: kafka
          image: wurstmeister/kafka:2.11-2.0.1
          ports:
            - containerPort: 9092
          env:
            - name: KAFKA_ADVERTISED_PORT
              value: "9092"
            - name: KAFKA_ADVERTISED_HOST_NAME
              value: "kafka-broker"
            - name: KAFKA_ZOOKEEPER_CONNECT
              value: zoo1:2181
            - name: KAFKA_CREATE_TOPICS
              value: "connections:1:2:compact"
            - name: KAFKA_LOG_DIRS
              value: /kafka/kafka-logs
            - name: KAFKA_BROKER_ID
              value: "1"
            - name: KAFKA_JMX_PORT
              value: "5555"
            - name: KAFKA_CLEANUP_POLICY
              value: "compact"
          volumeMounts:
            - name: kafka-volume
              mountPath: "/kafka/kafka-logs"
      volumes:
        - name: kafka-volume
          emptyDir: {}
