apiVersion: v1
kind: Service
metadata:
  annotations:
    meta.helm.sh/release-name: kafka
    meta.helm.sh/release-namespace: default
  labels:
    app.kubernetes.io/component: kafka-broker
    app.kubernetes.io/instance: kafka
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: kafka
    helm.sh/chart: kafka-0.21.5
  name: kafka-nodeport
spec:
  ports:
    - name: broker
      port: 9092
      targetPort: kafka
      nodePort: 30004
  selector:
    app.kubernetes.io/component: kafka-broker
    app.kubernetes.io/instance: kafka
    app.kubernetes.io/name: kafka
    service: udaconnect-api-connections
  type: NodePort
