apiVersion: v1
kind: Service
metadata:
  labels:
    service: udaconnect-api-connections
  name: udaconnect-api-connections
spec:
  ports:
    - name: "5000"
      port: 5000
      targetPort: 5000
      nodePort: 30001
  selector:
    service: udaconnect-api-connections
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: udaconnect-api-connections
  name: udaconnect-api-connections
spec:
  replicas: 1
  selector:
    matchLabels:
      service: udaconnect-api-connections
  template:
    metadata:
      labels:
        service: udaconnect-api-connections
    spec:
      containers:
        - image: juliangericke/nd064-message-passing:connections
          name: udaconnect-api-connections
          imagePullPolicy: Always
          env:
            - name: DB_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: api-env
                  key: DB_USERNAME
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: api-secret
                  key: DB_PASSWORD
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: api-env
                  key: DB_NAME
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: api-env
                  key: DB_HOST
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: api-env
                  key: DB_PORT
            - name: GRPC_URI
              valueFrom:
                configMapKeyRef:
                  name: api-env
                  key: GRPC_URI
            - name: PERSONS_URI
              valueFrom:
                configMapKeyRef:
                  name: api-env
                  key: PERSONS_URI
            - name: KAFKA_URI
              valueFrom:
                configMapKeyRef:
                  name: api-env
                  key: KAFKA_URI
            - name: KAFKA_TOPIC
              valueFrom:
                configMapKeyRef:
                  name: api-env
                  key: KAFKA_TOPIC
      restartPolicy: Always
