apiVersion: v1
kind: Service
metadata:
  labels:
    service: udaconnect-api-locations
  name: udaconnect-api-locations
spec:
  ports:
    - name: "5005"
      port: 5005
      targetPort: 5005
      nodePort: 30002
  selector:
    service: udaconnect-api-locations
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: udaconnect-api-locations
  name: udaconnect-api-locations
spec:
  replicas: 1
  selector:
    matchLabels:
      service: udaconnect-api-locations
  template:
    metadata:
      labels:
        service: udaconnect-api-locations
    spec:
      containers:
        - image: juliangericke/nd064-message-passing:locations
          name: udaconnect-api-locations
          imagePullPolicy: Always
          env:
            - name: DB_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: api-env
                  key: DB_USERNAME
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: api-secret
                  key: DB_PASSWORD
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: api-env
                  key: DB_NAME
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: api-env
                  key: DB_HOST
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: api-env
                  key: DB_PORT
      restartPolicy: Always
