---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: udaconnect-api-connections-consumer
  name: udaconnect-api-connections-consumer
spec:
  replicas: 1
  selector:
    matchLabels:
      service: udaconnect-api-connections-consumer
  template:
    metadata:
      labels:
        service: udaconnect-api-connections-consumer
    spec:
      containers:
        - image: juliangericke/nd064-message-passing:connections-consumer
          name: udaconnect-api-connections-consumer
          imagePullPolicy: Always
          env:
            - name: KAFKA_URI
              valueFrom:
                configMapKeyRef:
                  name: api-env
                  key: KAFKA_URI
            - name: KAFKA_TOPIC
              valueFrom:
                configMapKeyRef:
                  name: api-env
                  key: KAFKA_TOPIC
      restartPolicy: Always
