# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from protos import location_pb2 as protos_dot_location__pb2


class LocationServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Get = channel.unary_unary(
                '/LocationService/Get',
                request_serializer=protos_dot_location__pb2.Empty.SerializeToString,
                response_deserializer=protos_dot_location__pb2.LocationList.FromString,
                )
        self.GetLocation = channel.unary_unary(
                '/LocationService/GetLocation',
                request_serializer=protos_dot_location__pb2.GetLocationRequest.SerializeToString,
                response_deserializer=protos_dot_location__pb2.Location.FromString,
                )
        self.GetLocationRange = channel.unary_unary(
                '/LocationService/GetLocationRange',
                request_serializer=protos_dot_location__pb2.GetLocationRangeRequest.SerializeToString,
                response_deserializer=protos_dot_location__pb2.LocationList.FromString,
                )
        self.Create = channel.unary_unary(
                '/LocationService/Create',
                request_serializer=protos_dot_location__pb2.CreateLocationRequest.SerializeToString,
                response_deserializer=protos_dot_location__pb2.Location.FromString,
                )


class LocationServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Get(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetLocation(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetLocationRange(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Create(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_LocationServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Get': grpc.unary_unary_rpc_method_handler(
                    servicer.Get,
                    request_deserializer=protos_dot_location__pb2.Empty.FromString,
                    response_serializer=protos_dot_location__pb2.LocationList.SerializeToString,
            ),
            'GetLocation': grpc.unary_unary_rpc_method_handler(
                    servicer.GetLocation,
                    request_deserializer=protos_dot_location__pb2.GetLocationRequest.FromString,
                    response_serializer=protos_dot_location__pb2.Location.SerializeToString,
            ),
            'GetLocationRange': grpc.unary_unary_rpc_method_handler(
                    servicer.GetLocationRange,
                    request_deserializer=protos_dot_location__pb2.GetLocationRangeRequest.FromString,
                    response_serializer=protos_dot_location__pb2.LocationList.SerializeToString,
            ),
            'Create': grpc.unary_unary_rpc_method_handler(
                    servicer.Create,
                    request_deserializer=protos_dot_location__pb2.CreateLocationRequest.FromString,
                    response_serializer=protos_dot_location__pb2.Location.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'LocationService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class LocationService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Get(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/LocationService/Get',
            protos_dot_location__pb2.Empty.SerializeToString,
            protos_dot_location__pb2.LocationList.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetLocation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/LocationService/GetLocation',
            protos_dot_location__pb2.GetLocationRequest.SerializeToString,
            protos_dot_location__pb2.Location.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetLocationRange(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/LocationService/GetLocationRange',
            protos_dot_location__pb2.GetLocationRangeRequest.SerializeToString,
            protos_dot_location__pb2.LocationList.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Create(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/LocationService/Create',
            protos_dot_location__pb2.CreateLocationRequest.SerializeToString,
            protos_dot_location__pb2.Location.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
